M48
; DRILL file {KiCad (6.0.6-0)} date 2023 January 17, Tuesday 18:34:34
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-17T18:34:34+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X69.21Y-123.485
X74.99Y-123.485
T2
X54.0Y-65.0
X54.0Y-110.0
X96.0Y-65.0
X96.0Y-110.0
T0
M30
